[package]
name = "dungeoncrawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
legion = "=0.4.0"
serde = {version="=1.0.137"}
ron = "=0.7.0"

[profile.release]
lto = "thin"